version: "2"
services:

  snmp:
    image: quay.io/prometheus/snmp-exporter
    container_name: snmp_exporter
    volumes:
      - /opt/ipsec_monitor/snmp.yml:/etc/snmp_exporter/snmp.yml
    ports:
      - 9116:9116
      - 116:116/udp
    restart: always
    command: --config.file=/etc/snmp_exporter/snmp.yml


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      #- '--storage.tsdb.path=/prometheus'
      #- '--storage.tsdb.retention.time=365d'
    volumes:
      - /opt/ipsec_monitor/prometheus.yml:/etc/prometheus/prometheus.yml
     # - /opt/ipsec_monitor/prometheus-data:/prometheus

  grafana:

    image: grafana/grafana
    container_name: grafana
    restart: always

    environment:
      - GF_SECURITY_ADMIN_USER=admin1
      - GF_SECURITY_ADMIN_PASSWORD=admin1
      - GF_INSTALL_PLUGINS=raintank-worldping-app


    ports:
      - 3000:3000
